// src/pages/Blog.vue
<template>
  <Layout :class="'main'">
    <template slot="content">
      <div class="content-wrapper" v-for="post in posts" :key="post.id">
        <header class="entry-header">
          <h2 class="entry-title">{{ post.title }}</h2>
          <div class="posted">
            Posted
            <span class="by" v-if="post.author !== undefined">
              by
              <router-link :to="getAuthorLink(post.author)">
                {{ post.author.name }}
              </router-link>
            </span>
            at <span class="at">{{ getPostFormatedDate(post) }}</span>
          </div>
          <div class="tags-links" v-if="post.tags">
            <router-link v-for="tag in post.tags" :key="tag.id" :to="getTagLink(tag)">
              {{ tag.title }}
            </router-link>
          </div><!-- .tags-links -->
        </header><!-- .entry-header -->

        <div class="entry-content">{{ post.description }}</div>

        <footer class="entry-footer">
          <router-link :to="getPermalink(post)">
            Read more...
          </router-link>
          <div class="comments-count" v-if="post.comment_enabled && isFormatPost(post) === true">
            {{ post.count_comments }} Comments
          </div>
        </footer><!-- .entry-footer -->
      </div><!-- .content-wrapper -->
      <Paginate
        v-show="pages > 1"
        :page-count="pages"
        :click-handler="handleClick"
        :prev-text="'Prev'"
        :next-text="'Next'"
        :force-page="filters.page"
        :container-class="'pagination'">
      </Paginate>
    </template>
  </Layout>
</template>

<script type="text/javascript">

import helpers from '@/services/helpers'
import Layout from '@/components/Layout'
import Paginate from 'vuejs-paginate'

export default {
  name: 'Blog',
  components: {
    Layout,
    Paginate
  },
  async mounted () {
    if (this.$route.params.day !== undefined) {
      this.filters.search_created_at = this.$route.params.year + '-' + this.$route.params.month + '-' + this.$route.params.day
    } else if (this.$route.params.month !== undefined) {
      this.filters.search_created_at = this.$route.params.year + '-' + this.$route.params.month + '-'
    } else if (this.$route.params.year !== undefined) {
      this.filters.search_created_at = this.$route.params.year + '-'
    }

    if (this.$route.query.search !== undefined) {
      this.filters.search_content = this.$route.query.search
    }

    if (this.$route.query.page !== undefined) {
      this.filters.page = parseInt(this.$route.query.page)
    }

    this.$store.dispatch('updateTitle', 'Blog')
    let res = await this.$store.dispatch('fetchBlogPosts', {
      params: this.filters
    })
    this.posts = res.data
    this.pages = Math.ceil(res.meta.total / res.meta.size) || 0
  },
  methods: {
    ...helpers,
    async handleClick (n) {
      let qs = Object.assign({}, {...this.$route.query}, {page: n})
      await this.$router.push({
        path: this.$route.path,
        query: {...qs}
      })
    }
  },
  data () {
    return {
      pages: 1,
      posts: [],
      filters: {
        page: 1,
        order: 'created_at',
        sort: 'desc'
      }
    }
  }
}

</script>

// src/pages/Blog.jsx
import React from 'react'
import Post from '@/partials/Post'
import { connect } from 'react-redux'
import Layout from '@/partials/Layout'
import { withRouter } from 'react-router-dom'
import Pagination from '@/components/Pagination'
import contentAction from '@/services/content.action'

const mapStateToProps = state => {
  return {
    pagination: state.site.pagination,
    meta: state.content.posts.meta,
    data: state.content.posts.data
  }
}

const mapDispatchToProps = dispatch => {
  return {
    fetchAll: (payload) => {
      dispatch(contentAction.fetchBlogPosts(payload))
    }
  }
}

class Blog extends React.Component {

  componentDidMount = () => {

    let filters = {
      page: this.props.pagination.page,
      order: 'created_at',
      sort: 'desc',
      size: this.props.pagination.size
    }

    if (this.props.match.params.day !== undefined) {
      filters.search_created_at = this.props.match.params.year + '-' + this.props.match.params.month + '-' + this.props.match.params.day
    } else if (this.props.match.params.month !== undefined) {
      filters.search_created_at = this.props.match.params.year + '-' + this.props.match.params.month + '-'
    } else if (this.props.match.params.year !== undefined) {
      filters.search_created_at = this.props.match.params.year + '-'
    } else if (this.props.match.params.search !== undefined) {
      filters.search_content = this.props.match.params.search
    }

    this.props.fetchAll({
      params: {...filters}
    })
  }

  render = () => {
    return (
      <Layout>
        {
          this.props.data.map((post, index) => {
            return <Post key={index} detail={post}></Post>
          })
        }
        <Pagination currentPage={this.props.pagination.page} totalItems={this.props.meta.total} pageSize={this.props.pagination.size}></Pagination>
      </Layout>
    )
  }
}

export default withRouter(connect(mapStateToProps, mapDispatchToProps)(Blog))
