// src/components/CommentForm.jsx
import React from 'react'
import { connect } from 'react-redux'
import contentAction from '@/services/content.action'

const mapStateToProps = state => {
  return {
    user: state.auth.user
  }
}

const mapDispatchToProps = dispatch => {
  return {
    send: (payload) => {
      dispatch(contentAction.sendComment(payload))
    }
  }
}

class CommentForm extends React.Component {

  static defaultProps = {
    postId: ''
  }

  state = {
    name: '',
    email: '',
    website: '',
    content: ''
  }

  handleSubmit = (e) => {
    e.preventDefault()
    let payload = {
      post_id: this.props.postId,
      name: this.state.name,
      email: this.state.email,
      website: this.state.website,
      content: this.state.content
    }
    this.props.send(payload)
  }

  handleChangeName = (e) => {
    this.setState({
      name: e.target.value
    })
  }

  handleChangeEmail = (e) => {
    this.setState({
      email: e.target.value
    })
  }

  handleChangeWebsite = (e) => {
    this.setState({
      website: e.target.value
    })
  }

  handleChangeContent = (e) => {
    this.setState({
      content: e.target.value
    })
  }

  render = () => {
    return (
      <div className="comment-form">
        <form className="form-horizontal" onSubmit={this.handleSubmit}>
          <div className="form-group">
            <label className="control-label col-md-2">Name</label>
            <div className="col-md-6">
              <input type="text" className="form-control input-sm" value={this.state.name ? this.state.name : this.props.user.name} onChange={this.handleChangeName}/>
            </div>
          </div>
          <div className="form-group">
            <label className="control-label col-md-2">Email</label>
            <div className="col-md-6">
              <input type="text" className="form-control input-sm" value={this.state.email ? this.state.email : this.props.user.email} onChange={this.handleChangeEmail}/>
            </div>
          </div>
          <div className="form-group">
            <label className="control-label col-md-2">Website</label>
            <div className="col-md-6">
              <input type="text" className="form-control input-sm" value={this.state.website} onChange={this.handleChangeWebsite}/>
            </div>
          </div>
          <div className="form-group">
            <label className="control-label col-md-2">Message</label>
            <div className="col-md-10">
              <textarea className="form-control input-sm" value={this.state.content} onChange={this.handleChangeContent}></textarea>
            </div>
          </div>
          <div className="form-group">
            <div className="col-md-10 col-md-offset-2">
              <button type="submit" className="btn btn-sm btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    )
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(CommentForm)

// src/components/CommentForm.vue
<template>
  <div :class="className">
    <form class="form-horizontal" v-on:submit.prevent="handleSubmit">
      <div class="form-group" v-if="notLogin === true">
        <label class="control-label col-md-2">Name</label>
        <div class="col-md-6">
          <input type="text" v-model="name" class="form-control input-sm">
        </div>
      </div>
      <div class="form-group" v-if="notLogin === true">
        <label class="control-label col-md-2">Email</label>
        <div class="col-md-6">
          <input type="text" v-model="email" class="form-control input-sm">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2">Website</label>
        <div class="col-md-6">
          <input type="text" v-model="website" class="form-control input-sm">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2">Message</label>
        <div class="col-md-10">
          <textarea v-model="content" class="form-control input-sm"></textarea>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
          <button type="submit" class="btn btn-sm btn-primary">Submit</button>
        </div>
      </div>
    </form>
  </div>
</template>

<script type="text/javascript">

export default {
  props: {
    className: {
      type: String,
      default: 'comment-form'
    },
    post_id: {
      type: Number,
      required: true
    },
    name: {
      type: String
    },
    email: {
      type: String
    }
  },
  methods: {
    async handleSubmit () {
      await this.$store.dispatch('resetErrors')
      await this.$store.dispatch('sendComment', {
        id: this.post_id,
        params: {
          name: this.name,
          email: this.email,
          website: this.website,
          content: this.content
        }
      })
      this.content = ''
      this.$emit('sent')
    }
  },
  computed: {
    notLogin () {
      return this.me.id === 0
    },
    me () {
      return this.$store.getters.getMe()
    }
  },
  data () {
    return {
      website: '',
      content: ''
    }
  }
}

</script>
