// src/components/Menu.jsx
import React from 'react'
import PropTypes from 'prop-types'

class Menu extends React.Component {

  state = {
    opened: -1
  }

  static defaultProps = {
    lvl: 0,
    items: [],
    closeAll: false
  }

  handleClickMenu = (e) => {
    e.preventDefault()
    this.handleCollapse()
    if (e.target.href !== null && e.target.href.search(/^https?:\/\//) !== -1) {
      window.location.href = e.target.href
    } else {
      this.context.router.history.push(e.target.href)
    }
  }

  handleTriggerMenu = () => {
    
  }

  handleCollapse = () => {

  }

  makeItems = (items) => {
    let lists = []
    for (let a = 0; a < items.length; a++) {
      let item = []
      let key = `menu-item-lvl` + this.props.lvl + `-` + a
      if (items[a].children !== undefined && items[a].children.length !== 0) {
        item.push(<span className="carret" key={`li-span-` + key}>{ this.state.opened === a && this.props.closeAll === false ? `-` : `+` }</span>)
      }
      item.push(<a href={items[a].url} onClick={this.handleClickMenu} key={`li-a-` + key}>{items[a].label}</a>)
      if (items[a].children !== undefined && items[a].children.length !== 0 && this.state.opened === a) {
        item.push(<Menu key={key} className={`child-menu` + (this.state.opened === a && this.props.closeAll === false ? ` open` : ``)} collapse={this.handleCollapse} items={items[a].children} lvl={this.props.lvl + 1} closeAll={this.state.opened !== a}></Menu>)
      }
      lists.push(<li className={`menu-item-lvl-` + this.props.lvl + `-` + a} key={`li-` + key}>{item}</li>)
    }
    return lists
  }

  render = () => {
    return (
      <ul className={this.props.className}>{this.makeItems(this.props.items)}</ul>
    )
  }
}

Menu.propTypes = {
  lvl: PropTypes.number,
  items: PropTypes.array,
  closeAll: PropTypes.bool
}

export default Menu

// src/components/Menu.vue
<template>
  <ul v-if="items.length > 0">
    <li v-for="(item, index) in items" :key="'menu-item-lvl' + lvl + '-' + index">
      <span
        :class="'carret'"
        v-if="item.children !== undefined && item.children.length !== 0"
        v-on:click.prevent="triggerMenu(index)"
      >
        {{ opened === index && closeAll === false ? '-' : '+' }}
      </span>
      <a :href="item.url" v-on:click.prevent="clickMenu(item.url)">
        {{ item.label }}
      </a>
      <menu-item
        v-if="item.children !== undefined && item.children.length !== 0 && opened === index"
        v-on:menu-collapse="handleCollapse"
        :class="'child-menu' + (opened === index && closeAll === false ? ' open' : '')"
        :items="item.children" :lvl="lvl + 1"
        :closeAll="opened != index"
      />
    </li>
  </ul>
</template>

<script type="text/javascript">

export default {
  name: 'menu-item',
  props: {
    items: {
      type: Array,
      default: () => {
        return []
      }
    },
    lvl: {
      type: Number,
      default: 1
    },
    closeAll: {
      type: Boolean,
      default: false
    }
  },
  updated () {
    if (this.closeAll === true) {
      this.opened = -1
    }
  },
  methods: {
    async handleCollapse () {
      await this.$emit('close-menu')
      await this.$emit('menu-collapse')
      this.opened = -1
    },
    async triggerMenu (index) {
      if (this.opened === index) {
        this.opened = -1
      } else {
        this.opened = index
      }
      if (this.opened === -1) {
        this.$emit('close-menu')
      } else {
        this.$emit('open-menu')
      }
    },
    async clickMenu (url) {
      this.handleCollapse()
      if (url !== null && url.search(/^https?:\/\//) !== -1) {
        window.location.href = url
      } else {
        await this.$router.push(url)
      }
    }
  },
  data () {
    return {
      opened: -1
    }
  }
}

</script>
