// src/components/Search.vue
<template>
  <div>
    <form v-on:submit.prevent="handleSearch">
      <div class="search-form">
        <input type="text" class="form-control" v-model="search" placeholder="Put Keyword..">
      </div>
      <div class="search-button">
        <button type="submit" class="btn btn-info">Search</button>
      </div>
    </form>
  </div>
</template>

<script type="text/javascript">

import helpers from '@/services/helpers'

export default {
  mounted () {
    if (this.$route.query.search !== undefined) {
      this.search = this.$route.query.search
    }
  },
  methods: {
    ...helpers,
    handleSearch () {
      if (this.search.length > 0) {
        this.$router.push({
          path: '/',
          query: {
            search: this.search
          }
        })
      }
    }
  },
  data () {
    return {
      search: ''
    }
  }
}

</script>

// src/components/Search.jsx
import React from 'react'
import PropTypes from 'prop-types'

class Search extends React.Component {

  state = {
    searchValue: ''
  }

  static defaultProps = {
    placeholder: 'Put Keyword..'
  }

  handleSubmitForm = (e) => {
    e.preventDefault()
    if (this.state.searchValue.length > 0) {
      this.props.handler(this.state.searchValue)
    }
  }

  handleChange = (e) => {
    this.setState({searchValue: e.target.value})
  }

  render = () => {
    return (
      <div className={this.props.className}>
        <form onSubmit={this.handleSubmitForm}>
          <div className="search-form">
            <input type="text" className="form-control" value={this.state.searchValue} onChange={this.handleChange} placeholder={this.props.placeholder}/>
          </div>
          <div className="search-button">
            <button type="submit" className="btn btn-info">Search</button>
          </div>
        </form>
      </div>
    )
  }
}

Search.propTypes = {
  handler: PropTypes.func.isRequired,
  placeholder: PropTypes.string
}

export default Search
