// src/widgets/Menu.vue
<template>
  <div class="widget widget-menu" v-if="results.length > 0">
    <div class="widget-title">Menu</div>
    <div class="widget-body">
      <Menu :items="results" :class="'dor'" />
    </div>
  </div>
</template>

<script type="text/javascript">

import Menu from '@/components/Menu'

export default {
  components: {
    Menu
  },
  props: {
    results: {
      type: Array
    }
  },
  methods: {
    async handleClick (url) {
      if (url.search(/https?:\/\//) !== -1) {
        window.location.href = url
      } else {
        this.$router.push(url)
      }
    }
  }
}

</script>

// src/widgets/Menu.jsx
import React from 'react'
import PropTypes from 'prop-types'
import MenuComponent from '@/components/Menu'

class Menu extends React.Component {

  static defaultProps = {
    results: []
  }

  render = () => {
    return (
      <div className="widget widget-menu">
        <div className="widget-title">Menu</div>
        <div className="widget-body">
          <MenuComponent items={this.props.results} className="dor">
          </MenuComponent>
        </div>
      </div>
    )
  }
}

Menu.propTypes = {
  results: PropTypes.array
}

export default Menu
